In [2]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [17]:
np.zeros((2, 3))  # 2x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3, 3))   # 3x3 array of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.arange(0, 10, 2)  # Array of [0, 2, 4, 6, 8]

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 1, 5)  # 5 equally spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5, 7, 9]
print(a * b)  # [4, 10, 18]

[5 7 9]
[ 4 10 18]


In [23]:
import numpy as np

# Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Using np.dot()
result_dot = np.dot(A, B)

# Using @ operator
result_at = A @ B

print("Result of Matrix Multiplication:")
print(result_dot)

Result of Matrix Multiplication:
[[19 22]
 [43 50]]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])  # 6
print(arr[:, 1])  # [2, 5]

6
[2 5]


In [27]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr[0, 1])      # Access 2nd element in 1st row
print(arr[:, 1])      # Access the 2nd column
print(arr[1:3, 0:2])  # Slice a subarray


2
[2 5 8]
[[4 5]
 [7 8]]


In [29]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A + B)  # Element-wise addition
print(A * B)  # Element-wise multiplication
print(np.dot(A, B))  # Dot product

[5 7 9]
[ 4 10 18]
32


In [31]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr), np.max(arr), np.min(arr))

3.0 5 1


In [36]:
arr = np.arange(1, 13)
print(arr) # this is a one dimension array 
reshaped = arr.reshape(3, 4)
print(reshaped) # This is a 3 X 4 array


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

flat_arr = arr.flatten()
print(flat_arr)  # Output: [1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [46]:
image = np.array([[255, 0, 255],
                  [0, 255, 0],
                  [255, 0, 255]])

flat_image = image.flatten()
print(flat_image)  # Output: [255   0 255   0 255   0 255   0 255]

[255   0 255   0 255   0 255   0 255]


In [44]:
inputs = np.array([1, 2])
weights = np.array([[0.1, 0.2],
                    [0.4, 0.5]])
outputs = np.dot(inputs, weights)
print(outputs)  # Output of the layer


[0.9 1.2]
